services:
  postgres:
    image: postgres:15.1-alpine3.17
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexanode
    volumes:
      - hexanode_postgres:/var/lib/postgresql/data

volumes:
  hexanode_postgres:
    driver: local
